"""Add payment_link and pdf_url

Revision ID: 27e49a83fc9e
Revises: 8c92eb329a66
Create Date: 2026-02-17 19:04:08.693792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27e49a83fc9e'
down_revision = '8c92eb329a66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_link', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('pdf_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_column('pdf_url')
        batch_op.drop_column('payment_link')

    # ### end Alembic commands ###
