"""add ai_instructions

Revision ID: 4d420b1b02ee
Revises: d5a2ccb26a5b
Create Date: 2026-03-01 13:14:22.672246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d420b1b02ee'
down_revision = 'd5a2ccb26a5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_instructions', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('ai_instructions')

    # ### end Alembic commands ###
